config/routes.rb
Rails.application.routes.draw do
  
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  Blacklight::Marc.add_routes(self)
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  root to: "catalog#index"
    concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end

  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get 'advanced' => 'advanced#index', as: 'advanced_search'
  match 'advanced/range_limit', :to => 'advanced#range_limit', :as => 'catalog_range_limit', :via=>[:get, :post]

  resources :forms 
  post "forms/send_email" => "forms#send_email"

end

app/controllers/blacklight_advanced_search/advanced_controller.rb
# frozen_string_literal: true

# Need to sub-class CatalogController so we get all other plugins behavior
# for our own "inside a search context" lookup of facets.
class BlacklightAdvancedSearch::AdvancedController < CatalogController
  helper BlacklightRangeLimit::ViewHelperOverride
  helper RangeLimitHelper

  def index
    @response = get_advanced_search_facets unless request.method == :post
  end

  protected

  # Override to use the engine routes
  def search_action_url(options = {})
    blacklight_advanced_search_engine.url_for(options.merge(action: 'index'))
  end

  def get_advanced_search_facets
    # We want to find the facets available for the current search, but:
    # * IGNORING current query (add in facets_for_advanced_search_form filter)
    # * IGNORING current advanced search facets (remove add_advanced_search_to_solr filter)
    response, _ = search_results(params) do |search_builder|
      search_builder.except(:add_advanced_search_to_solr).append(:facets_for_advanced_search_form)
    end

    response
  end
end

app/views/advanced/_advanced_search_form.html.erb
  <% unless (search_context_str = render_search_to_s( advanced_search_context)).blank? %>
    <div class="constraints well search_history">
      <h4><%= t 'blacklight_advanced_search.form.search_context' %></h4>
      <%= search_context_str %>
    </div>
  <% end %>

<%= form_tag search_catalog_path, :class => 'advanced form-horizontal', :method => :get do  %>

  <%= render_hash_as_hidden_fields(search_state.params_for_search(advanced_search_context)) %>

  <div class="input-criteria">

      <div class="query-criteria">
        <h3 class="query-criteria-heading">
          <%= t('blacklight_advanced_search.form.query_criteria_heading_html', :select_menu =>  select_menu_for_field_operator ) %> 
        </h3>

        <div id="advanced_search">
          <%= render 'advanced/advanced_search_fields' %>
        </div>
      </div>  
      <div class="sort-submit-buttons clearfix">
    <%= render 'advanced_search_submit_btns' %>
  </div>
      
      <div class="limit-criteria">
        <h3 class="limit-criteria-heading"><%= t('blacklight_advanced_search.form.limit_criteria_heading_html')%></h3>

        <div id="advanced_search_facets" class="limit_input">
          <% if blacklight_config.try(:advanced_search).try {|h| h[:form_facet_partial] } %>
            <%= render blacklight_config.advanced_search[:form_facet_partial] %>
          <% else %>
            <%= render 'advanced_search_facets' %>
          <% end %>
        </div>
      </div>
  </div>

  <hr>



<% end %>

app/views/advanced/index.html.erb
<% @page_title = "More Search Options - #{application_name}" %>

<div class="advanced-search-form col-sm-12">

    <h1 class="advanced page-header">
        <%= t('blacklight_advanced_search.form.title') %>
        <%= link_to t('blacklight_advanced_search.form.start_over'), root_path(:lib => $brand), :class =>"btn btn-default pull-right advanced-search-start-over" %>
    </h1>

    <div class="row">

        <div class="col-md-8">
            <%= render 'advanced_search_form' %>
        </div>
        <div class="col-md-4">
            <%= render "advanced_search_help" %>
        </div>

    </div>

</div>